### ISSUE TITLE
Please add a repo description

### ISSUE THREAD

**Issue by waldyrious** [aharris88/awesome-ipsum#1]
It is currently blank ("No description or website provided."). I searched for "awesome lorem ipsum" and only found @templeman's at https://github.com/templeman/awesome-ipsum. I think yours should be findable too :) (although I'd personally prefer if efforts were merged into a single repo -- but that's a topic for another discussion :))

**Comment by waldyrious** [comment]
@aharris88 ping :)

**Comment by aharris88** [comment]
I added a description. Thanks. I agree they should be merged.
